### ISSUE TITLE
Mixing HTML and JavaScript makes me sad :-(

### ISSUE THREAD

**Issue by briandk** [cherylmedley/otIntJS#10]
Again, I'm not a pro web developer, but when I can I try to have my JavaScript live in separate source files that get linked in. So, instead of an HTML file with

``` html

<script>

// some JavaScript code

</script>
```

I would [link in the JavaScript code](https://github.com/briandk/gitvisualizations/blob/master/CodeTimeline/timeline_view.mustache#L91), from [a separate JavaScript file](https://github.com/briandk/gitvisualizations/blob/master/CodeTimeline/externalFiles/Timeline.js), in my html boilerplate.

Of course, I've also totally put `<scripts>` in my HTML [when it was convenient](https://github.com/briandk/gitvisualizations/blob/master/CodeTimeline/timeline_view.mustache#L88-L90), so it's not like I'm innocent here.

**Comment by briandk** [comment]
@cherylmedley - You might be all like, "Wait, Brian. That last snippet of code where you mixed JavaScript and HTML looks all weird."

As a reminder, [here's a case](https://github.com/briandk/gitvisualizations/blob/master/CodeTimeline/timeline_view.mustache#L88-L90) where I put a tiny `<script>` right in my HTML file:

``` html
<script type="text/javascript">
    var revisions = [{{{revisions}}}];
</script>
```

And as you go line by line, you're like:
1. OK. I'm fine with you invoking a `<script>` and passing an attribute to say what type of script it is.
2. Wait WHAT?
3. Right, you close the script out. Makes sense.

## What the junk is happening in that second line?

You're probably OK with declaring normal variables in JavaScript, like this:

``` js
var myAge = 5;
```

You may even be OK with declaring a variable and assigning an array as its value

``` js
var ninjaTurtles = ["Leonardo", "Donatello", "Raphael", "Michaelangelo"];
```

So, if we break down the right-hand side of [that line](https://github.com/briandk/gitvisualizations/blob/master/CodeTimeline/timeline_view.mustache#L89) from the outside-in, what I'm doing is assigning some array as the value of the variable `revisions`. As background, this is JavaScript code that deals with collecting a list of all the times a student revised a file, so `revisions` is an array of identifiers for each revision of a file. So far, so good. The right-hand-side [of that statement](https://github.com/briandk/gitvisualizations/blob/master/CodeTimeline/timeline_view.mustache#L89) is bounded by square brackets (`[ ]`), which is a pretty strong clue that what I've got is an array.

## Right, but what's with the curly braces?

The curly braces are part of a templating system I used called [Mustache](http://mustache.github.io/mustache.5.html). Mustache is a way for developers to have webpages that are generated via some other code that runs and poops out its values into a template. In this case, what I wanted was to have a list of revisions (that I would not need to specify up front), but that would be filled in as HTML later whenever my python script was run.

SO, now we get to the curly-braces. The curly-braces actually work like this.
1. When my python script runs,
2. It looks at the [mustache file](https://github.com/briandk/gitvisualizations/blob/master/CodeTimeline/timeline_view.mustache),
3. And finds [entities that are bounded by double curly-braces](https://github.com/briandk/gitvisualizations/blob/master/CodeTimeline/timeline_view.mustache#L89) `{{like this}}`
4. And uses Python code to compute what should go inside those entites (in this case a list of revisions),
5. Then replaces the literal string `{{revisions}}` in my .mustache file with the text of what's actually supposed to be in that array: `["bd31a3","47f449",...]`

## But wait, those are TRIPLE curly braces

Yeah, I know. Which is weird. Near as I can tell, it goes back to this commit where I deliberately [added a third set of curly-braces](https://github.com/briandk/gitvisualizations/commit/91c1867188462f2e93e1985ac371cf739ad53707#diff-1):

https://github.com/briandk/gitvisualizations/commit/91c1867188462f2e93e1985ac371cf739ad53707#diff-1

I am still not sure why I did that, and I also don't know whether they're necessary because it's been awhile.

**Comment by cherylmedley** [comment]
Thanks for commenting, Brian! I don't remember mixing javascript and HTML except in my test page where I was trying to eliminate confounding factors by putting stuff all in the same place (for learning purposes, not best practice) . Are there places in the actual file I did that? I tried to keep things separate there.

**Comment by briandk** [comment]
@cherylmedley - Now that I look back, I can't find where you mixed it either. I'm not sure what I was on about. Sorry!
