### ISSUE TITLE
Add <title> for best practice HTML

### ISSUE THREAD

**Issue by cherylmedley** [cherylmedley/otIntJS#16]
https://github.com/KyleMit/otIntJS/commit/f7b126039f98e6dada4179bc3253997aac8e5c7a

**Comment by cherylmedley** [comment]
@KyleMit, do you know how to close issues by using the "Close" or "Fix" in a commit? I tried to follow the examples on [this page](https://help.github.com/articles/closing-issues-via-commit-messages/), but it hasn't been working. It seems to just mark it as a reference rather than as an action.

![image](https://cloud.githubusercontent.com/assets/9951863/5248755/acc935cc-794b-11e4-9ce4-3d6a7bac3446.png)

**Comment by KyleMit** [comment]
Your syntax looks fine.  There was a (good) change to the way smart commits were pushed onto issues.  Closing an issue via commit message won't actually close the issue _until_ the commit has been merged into your master branch.  That way things don't get prematurely closed if they haven't been accepted yet.

See more here: https://github.com/blog/1386-closing-issues-via-commit-messages

![Example](https://cloud.githubusercontent.com/assets/4307307/5251544/581784ac-7964-11e4-946e-b61c0b52ce8b.png)

**Comment by cherylmedley** [comment]
Ah-ha. Got it. So it only counts against the master. Thanks for the tip.
